export const themes = {
  dark: {
    bg:        '#0D0D14',
    bgCard:    '#161622',
    bgDeep:    '#0A0A10',
    sidebar:   '#12121C',
    border:    '#1E1E2E',
    borderMid: '#2A2A3A',
    text:      '#E0DEF0',
    textMid:   '#9A9AB0',
    textDim:   '#4A4A6A',
    textFaint: '#2A2A4A',
    purple:    '#6C63FF',
    green:     '#10B981',
    amber:     '#F59E0B',
    red:       '#EF4444',
    teal:      '#059669',
    violet:    '#8B5CF6',
  },
  light: {
    bg:        '#F5F5FA',
    bgCard:    '#FFFFFF',
    bgDeep:    '#EDEDF5',
    sidebar:   '#FFFFFF',
    border:    '#E2E2EC',
    borderMid: '#D0D0E0',
    text:      '#1A1A2E',
    textMid:   '#4A4A6A',
    textDim:   '#7A7A9A',
    textFaint: '#ABABC0',
    purple:    '#6C63FF',
    green:     '#059669',
    amber:     '#D97706',
    red:       '#DC2626',
    teal:      '#047857',
    violet:    '#7C3AED',
  },
};

export let C = { ...themes.dark };

export const S = {
  card: {
    background: '#161622',
    border: '1px solid #1E1E2E',
    borderRadius: 13,
    padding: '14px 16px',
    marginBottom: 9,
  },
  lbl: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#4A4A6A',
    marginBottom: 8,
    display: 'block',
  },
  inp: {
    background: '#0D0D14',
    border: '1px solid #1E1E2E',
    borderRadius: 8,
    padding: '8px 11px',
    fontSize: 14,
    color: '#E0DEF0',
    width: '100%',
    boxSizing: 'border-box',
    outline: 'none',
  },
  ta: {
    background: '#0D0D14',
    border: '1px solid #1E1E2E',
    borderRadius: 8,
    padding: '8px 11px',
    fontSize: 14,
    color: '#E0DEF0',
    width: '100%',
    boxSizing: 'border-box',
    outline: 'none',
    resize: 'vertical',
    lineHeight: 1.7,
  },
  sel: {
    background: '#0D0D14',
    border: '1px solid #1E1E2E',
    borderRadius: 8,
    padding: '8px 11px',
    fontSize: 13,
    color: '#E0DEF0',
    outline: 'none',
    cursor: 'pointer',
  },
  btn: (color = '#6C63FF') => ({
    background: color,
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '8px 15px',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  }),
  ghost: {
    background: '#0D0D14',
    color: '#9A9AB0',
    border: '1px solid #1E1E2E',
    borderRadius: 8,
    padding: '8px 12px',
    fontSize: 13,
    cursor: 'pointer',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '9px 0',
    borderBottom: '1px solid #1E1E2E',
  },
  pill: (color) => ({
    display: 'inline-block',
    background: color + '22',
    color,
    fontSize: 11,
    borderRadius: 99,
    padding: '2px 8px',
    marginLeft: 4,
  }),
  bdg: (bg, color) => ({
    background: bg,
    color,
    borderRadius: 99,
    padding: '2px 9px',
    fontSize: 11,
    fontWeight: 600,
  }),
  statCard: {
    background: '#0D0D14',
    border: '1px solid #1E1E2E',
    borderRadius: 11,
    padding: 13,
    textAlign: 'center',
  },
};
