export const themes = {
  dark: {
    bg:       '#0D1117',
    bgCard:   '#161B27',
    sidebar:  '#0D1117',
    border:   '#1E2433',
    borderMid:'#2A3045',
    text:     '#F0F0F8',
    textMid:  '#A0A8C0',
    textDim:  '#606880',
    textFaint:'#3A4055',
    purple:   '#3B82F6',
    green:    '#22C55E',
    red:      '#EF4444',
    amber:    '#F59E0B',
    teal:     '#06B6D4',
    violet:   '#8B5CF6',
    blue:     '#3B82F6',
  },
  light: {
    bg:       '#F4F6FB',
    bgCard:   '#FFFFFF',
    sidebar:  '#FFFFFF',
    border:   '#E2E8F0',
    borderMid:'#CBD5E1',
    text:     '#0F172A',
    textMid:  '#475569',
    textDim:  '#94A3B8',
    textFaint:'#CBD5E1',
    purple:   '#2563EB',
    green:    '#16A34A',
    red:      '#DC2626',
    amber:    '#D97706',
    teal:     '#0891B2',
    violet:   '#7C3AED',
    blue:     '#2563EB',
  },
};

export const C = { ...themes.dark };

export const S = {
  card: {
    background: C.bgCard,
    border: '1px solid ' + C.border,
    borderRadius: 13,
    padding: '14px 16px',
    marginBottom: 9,
  },
  inp: {
    width: '100%',
    background: C.bg,
    border: '1px solid ' + C.border,
    borderRadius: 8,
    padding: '9px 12px',
    color: C.text,
    fontSize: 13,
    outline: 'none',
    fontFamily: "'Inter', sans-serif",
  },
  btn: (color) => ({
    background: color,
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '8px 14px',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: "'Inter', sans-serif",
  }),
  ghost: {
    background: 'none',
    border: '1px solid ' + C.border,
    borderRadius: 8,
    padding: '7px 12px',
    color: C.textMid,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: "'Inter', sans-serif",
  },
  ta: {
    width: '100%',
    background: C.bg,
    border: '1px solid ' + C.border,
    borderRadius: 8,
    padding: '10px 12px',
    color: C.text,
    fontSize: 13,
    outline: 'none',
    fontFamily: "'Inter', sans-serif",
    resize: 'vertical',
    lineHeight: 1.6,
  },
  lbl: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: C.textDim,
    display: 'block',
    marginBottom: 8,
  },
  pill: (color) => ({
    display: 'inline-block',
    background: color + '22',
    color: color,
    border: '1px solid ' + color + '44',
    borderRadius: 99,
    padding: '2px 8px',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.04em',
  }),
  bdg: (color) => ({
    display: 'inline-block',
    background: color + '18',
    color: color,
    borderRadius: 6,
    padding: '2px 7px',
    fontSize: 10,
    fontWeight: 700,
  }),
};
